#!/usr/bin/bash

export USE_LTO=1
export ROCKSDB_DISABLE_GFLAGS=1
export TOPLING_ZIP_TABLE_TRIAL_DAYS=90
make UPDATE_REPO=0 DEBUG_LEVEL=0 DISABLE_JEMALLOC=1 TOPLING_USE_DYNAMIC_TLS=1 -j60 libsnappy.a liblz4.a libbz2.a
make rocksdbjava install-dcompact -j`nproc`
    DEBUG_LEVEL=0 UPDATE_REPO=0 PREFIX=install-here \
    DISABLE_JEMALLOC=1 TOPLING_USE_DYNAMIC_TLS=1 \
    STRIP_DEBUG_INFO=1 ROCKSDB_JAR_WITH_DYNAMIC_LIBS=1

